
CREATE TABLE USERS (
    userID VARCHAR(36) NOT NULL PRIMARY KEY,
    username VARCHAR(255),
    email VARCHAR (255),
    userPass VARCHAR (255)
);

CREATE TABLE USER_TYPE (
    userID VARCHAR(36) NOT NULL PRIMARY KEY,
    userType VARCHAR (36),
    FOREIGN KEY (userID) REFERENCES USERS(userID)
);

CREATE TABLE RESTAURANT(
    restaurantID VARCHAR(36) NOT NULL PRIMARY KEY,
    restaurantName VARCHAR(255),
    pictureURL VARCHAR(255)
);

CREATE TABLE ORDERS(
    orderID VARCHAR(36) NOT NULL PRIMARY KEY,
    customerID VARCHAR (36),
    staffID VARCHAR (36),
    restaurantID VARCHAR (36),
    orderCreatedAt DATETIME,
    itemDescription VARCHAR(255),
    FOREIGN KEY (customerID) REFERENCES USERS(userID),
    FOREIGN KEY (staffID) REFERENCES USERS(userID),
    FOREIGN KEY (restaurantID) REFERENCES RESTAURANT(restaurantID)
);

CREATE TABLE ORDERSTATUS(
    orderID VARCHAR(36) NOT NULL PRIMARY KEY,
    orderStatus VARCHAR (255),
    FOREIGN KEY (orderID) REFERENCES ORDERS(orderID)
);

CREATE TABLE ORDERRATING(
    orderID VARCHAR(36) NOT NULL PRIMARY KEY,
    rating VARCHAR (255),
    FOREIGN KEY (orderID) REFERENCES ORDERS(orderID)
);
